//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC6_sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subscription
    {
        public int subscription_id { get; set; }
        public Nullable<int> cus_id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
