//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_class
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int cus_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
