//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_class
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_plan
    {
        public int plan_id { get; set; }
        public string plan_name { get; set; }
        public string plan_code { get; set; }
        public Nullable<double> interval { get; set; }
        public Nullable<int> trail_period { get; set; }
        public Nullable<double> amount { get; set; }
    }
}
