//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class chargeInfo
    {
        public int id { get; set; }
        public string infomation { get; set; }
        public string domain { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string requestJson { get; set; }
        public string type { get; set; }
    }
}
