//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientPaymentHistory
    {
        public string id { get; set; }
        public Nullable<System.DateTime> receivedDate { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string domain { get; set; }
        public Nullable<double> amount { get; set; }
        public string currency { get; set; }
        public string customerId { get; set; }
        public string userid { get; set; }
        public string merchant { get; set; }
        public Nullable<int> chargeInfoId { get; set; }
        public string orderId { get; set; }
        public string guTranId { get; set; }
        public string accountId { get; set; }
        public string subscriptionId { get; set; }
        public string cardInfo { get; set; }
        public string paymentGateway { get; set; }
        public string otherInfo { get; set; }
    }
}
