//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateTable
    {
        public System.DateTime date { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<System.DateTime> FirstOfMonth { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<int> ISOweek { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<int> quarter { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<System.DateTime> FirstOfYear { get; set; }
        public string Style112 { get; set; }
        public string Style101 { get; set; }
    }
}
