//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class earning
    {
        public int earn_id { get; set; }
        public string domain { get; set; }
        public string earn_type { get; set; }
        public Nullable<double> earn_value { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<int> retryCount { get; set; }
        public Nullable<int> chargeInfoId { get; set; }
        public Nullable<int> periodStart { get; set; }
        public Nullable<int> periodEnd { get; set; }
        public Nullable<System.DateTime> receievedDate { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string stripeChargeId { get; set; }
    }
}
