//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cloudchargepaymentEntities : DbContext
    {
        public cloudchargepaymentEntities()
            : base("name=cloudchargepaymentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C2checkout_IPN_logs> C2checkout_IPN_logs { get; set; }
        public virtual DbSet<C2checkoutClient> C2checkoutClient { get; set; }
        public virtual DbSet<authorizeClient> authorizeClients { get; set; }
        public virtual DbSet<braintreeClient> braintreeClients { get; set; }
        public virtual DbSet<chargeInfo> chargeInfoes { get; set; }
        public virtual DbSet<clientPaymentHistory> clientPaymentHistories { get; set; }
        public virtual DbSet<clientPaymentRefundHistory> clientPaymentRefundHistories { get; set; }
        public virtual DbSet<companyDomain> companyDomains { get; set; }
        public virtual DbSet<DateTable> DateTables { get; set; }
        public virtual DbSet<earning> earnings { get; set; }
        public virtual DbSet<IPN_logs> IPN_logs { get; set; }
        public virtual DbSet<msg_logs> msg_logs { get; set; }
        public virtual DbSet<paymentHistory> paymentHistories { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<quickbookClient> quickbookClients { get; set; }
        public virtual DbSet<stripeAcc> stripeAccs { get; set; }
        public virtual DbSet<stripeClient> stripeClients { get; set; }
        public virtual DbSet<subscription> subscriptions { get; set; }
        public virtual DbSet<subscriptionHistory> subscriptionHistories { get; set; }
        public virtual DbSet<testClient> testClients { get; set; }
        public virtual DbSet<UserMapping> UserMappings { get; set; }
        public virtual DbSet<worldpayClient> worldpayClients { get; set; }
        public virtual DbSet<paymentGateway> paymentGateways { get; set; }
    }
}
