//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_logs
    {
        public int Id { get; set; }
        public string IPN_logscol { get; set; }
        public string type { get; set; }
        public string merchant { get; set; }
        public string typeId { get; set; }
        public Nullable<System.DateTime> receivedDate { get; set; }
    }
}
