//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentGateway
    {
        public int id { get; set; }
        public string paymentGateway1 { get; set; }
        public Nullable<bool> status { get; set; }
        public string supportCurrency { get; set; }
    }
}
