//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string product_picture { get; set; }
        public Nullable<double> price_of_unit { get; set; }
        public Nullable<long> apply_tax { get; set; }
        public Nullable<double> tax { get; set; }
        public string manufactured_date { get; set; }
        public int productId { get; set; }
        public string product_name { get; set; }
        public string category { get; set; }
        public string createddate { get; set; }
        public string attachment { get; set; }
        public string tags { get; set; }
        public string uom { get; set; }
        public string brand { get; set; }
        public Nullable<long> sku { get; set; }
        public Nullable<double> minimun_stock_level { get; set; }
        public string expiry_date { get; set; }
        public string descroption { get; set; }
        public Nullable<double> quantity_of_unit { get; set; }
        public Nullable<double> cost_price { get; set; }
        public string code { get; set; }
        public Nullable<long> status { get; set; }
        public string createuser { get; set; }
        public string trackInventory { get; set; }
        public string productscol { get; set; }
    }
}
