//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class quickbookClient
    {
        public string domain { get; set; }
        public string realmId { get; set; }
        public string oauthToken { get; set; }
        public string oauth_token_secret { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
