//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class stripeAcc
    {
        public string id { get; set; }
        public string ApiKey_Test { get; set; }
        public string ApiKey_Live { get; set; }
        public string Client_Id_Test { get; set; }
        public string Client_Id_Live { get; set; }
    }
}
