//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class stripeClient
    {
        public int Id { get; set; }
        public string domain { get; set; }
        public string ApiKey { get; set; }
        public string PubKey { get; set; }
        public string RefreshKey { get; set; }
        public string AccKey { get; set; }
    }
}
