//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriptionHistory
    {
        public int id { get; set; }
        public string subscriptionId { get; set; }
        public string action { get; set; }
        public Nullable<double> amount { get; set; }
        public string currency { get; set; }
        public string interval { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> receivedDate { get; set; }
        public string merchant { get; set; }
        public string domain { get; set; }
        public string plan { get; set; }
    }
}
