//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public int id { get; set; }
        public string domain { get; set; }
        public string subscriptionId { get; set; }
        public string plan { get; set; }
        public Nullable<double> amount { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public string gatewayType { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string otherInfo { get; set; }
        public Nullable<int> currentPeriod { get; set; }
        public Nullable<int> currentPeriodEnd { get; set; }
        public Nullable<int> createdDate { get; set; }
    }
}
