//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMapping
    {
        public string userId { get; set; }
        public string cusID { get; set; }
        public string gatewayType { get; set; }
        public string subscriptionId { get; set; }
        public string createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string plan { get; set; }
        public string paidDate { get; set; }
        public string planStatus { get; set; }
        public string planType { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> disconnectedDate { get; set; }
    }
}
