//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_course_subject
    {
        public int course_subject_id { get; set; }
        public int course_id { get; set; }
        public int subject_id { get; set; }
    
        public virtual tbl_course tbl_course { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
    }
}
